### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by mimoo** [mimoo/noname#5]
Roadmap of the proof of concept:

- [x] [`arithmetic.no`](/data/arithmetic.no) (simple arithmetic)
- [x] `[public_output.no`](/data/public_output.no) (returns a public output)
- [x] `[poseidon.no`](/data/poseidon.no) (uses the poseidon function)
- [x] make sure wiring debug shows you the var location, not the expression
- [x] wiring in kimchi gates
- [x] bool.no
- [x] mutable variable enforced by type checker
- [x] enforce scoping on the circuit writer side
- [x] for_loop.no
- [x] array.no
- [x] types.no (custom types)
- [x] const.no
- [ ] functions.no
- [ ] methods.no
- [ ] sudoku.no
- [ ] hints in the language
- [ ] resolving third-party libraries
- [ ] support generics in the stdlib? (e.g. `assert_eq`)
- [ ] release with cargo release

refactors:

- [ ] remove `TyKind::BigInt` and use `TyKind::Field` instead. If we need to track if it's a constant (for for loops, for example), then we can perhaps have `TyKind::Field{ is_constant: bool }`?
- [ ] document value::linercombination because it makes no sense perhaps? (and rename value to HowToCompute or smthg like that?)
- [ ] document why Expr has `typ` in the parser
- [ ] remove span from Constant, I don't think it's useful

**Comment by mimoo** [comment]
using projects intead: https://github.com/users/mimoo/projects/1
